def name_gen():
    import random
    first_name = [
        "Kelvin",
        "Joyce",
        "Bruce",
        "Robert",
        "Blake",
        "Abraham",
        "Melissa",
        "Alberta",
        "Owen",
        "Chester",
        "Edwin",
        "Henry",
        "Adam",
        "Aldus",
        "Ryan",
        "Cadie",
        "Victor",
        "Tara",
        "Naomi",
        "Edgar",
        "Sophia",
        "Abraham",
        "Martin",
        "Martin",
        "Maximilian",
        "Derek",
        "Maddie",
        "Sawyer",
        "Jenna",
        "Naomi",
        "Lydia",
        "Sam",
        "Dale",
        "Martin",
        "Charlotte",
        "Blake",
        "Luke",
        "Adelaide",
        "Camila",
        "Sawyer",
    ]

    surname = [
        "Johnson",
        "Wells",
        "Reed",
        "Mason",
        "Hill",
        "Ferguson",
        "Hill",
        "Murphy",
        "Kelley",
        "West",
        "Murphy",
        "Harris",
        "Ferguson",
        "Russell",
        "Sullivan",
        "Douglas",
        "Brooks",
        "Dixon",
        "Thompson",
        "Scott",
        "Johnston",
        "Adams",
        "Sullivan",
        "Cunningham",
        "Allen",
        "Kelly",
        "Roberts",
        "Howard",
        "Carroll",
        "Morris",
        "Morgan",
        "Sullivan",
        "Mitchell",
        "Riley",
        "Walker",
        "Myers",
        "Hawkins",
    ]

    return random.choice(first_name), random.choice(surname)
  
  
